name: example
description: Examples for sketch

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  complex: ^0.6.1
  sketch:
    # git: https://github.com/BlankSTDIO/sketch.git
    path: ../
  flutter:
    sdk: flutter

