name: example
description: Examples for sketch

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sketch:
    git: https://github.com/BlankSTDIO/sketch.git
  flutter:
    sdk: flutter

