name: sketch
description: A new Flutter package project.
version: 0.0.1
authors:
  - ErikWDev@gmail.com
homepage: https://www.github.com/BlankSTDIO/sketch
repository: https://www.github.com/BlankSTDIO/sketch

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

